-- Wara baseline schema (migration 0001).
--
-- Derived from Toasty's `push_schema()` output (captured via `pg_dump
-- --schema-only`), so the resulting schema matches Toasty's runtime expectations
-- exactly: same columns, same `<table>_pkey` primary-key names (Postgres' default
-- naming), and the same index names Toasty generates.
--
-- Written to be idempotent and adoptable: `IF NOT EXISTS` on every object and the
-- primary key inlined in the table body. A fresh database gets the full schema; a
-- database already created by `push_schema()` (which has the tables but no
-- migration history) adopts cleanly as a no-op and is recorded as applied. This is
-- what lets existing development databases upgrade without data loss.
--
-- Do not edit this file after it ships; add a new NNNN_*.sql migration instead. All
-- objects are schema-qualified (public.) and contain no search_path or psql
-- meta-commands so the migration runner can apply it with batch_execute.

CREATE TABLE IF NOT EXISTS public.app_service_records (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    environment_id uuid NOT NULL,
    name text NOT NULL,
    deploy_kind text NOT NULL,
    image text,
    compose_file text,
    dockerfile text,
    internal_port integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.deployment_records (
    id uuid NOT NULL,
    service_id uuid NOT NULL,
    status text NOT NULL,
    workflow_id text NOT NULL,
    output text NOT NULL,
    created_at text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.docker_credential_records (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    registry text NOT NULL,
    username text NOT NULL,
    encrypted_password text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.domain_records (
    id uuid NOT NULL,
    service_id uuid NOT NULL,
    hostname text NOT NULL,
    proxy text NOT NULL,
    tls_enabled boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.env_var_records (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    environment_id uuid,
    service_id uuid,
    key text NOT NULL,
    encrypted_value text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.environments (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.project_template_records (
    id uuid NOT NULL,
    source_project_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.projects (
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.server_records (
    id uuid NOT NULL,
    name text NOT NULL,
    host text NOT NULL,
    port integer NOT NULL,
    username text NOT NULL,
    public_key text NOT NULL,
    private_key_fingerprint text NOT NULL,
    encrypted_private_key text NOT NULL,
    encrypted_private_key_passphrase text,
    default_proxy text NOT NULL,
    docker_status text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_invite_records (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash text NOT NULL,
    expires_at text NOT NULL,
    accepted_at text NOT NULL,
    created_at text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_records (
    id uuid NOT NULL,
    email text NOT NULL,
    name text NOT NULL,
    role text NOT NULL,
    status text NOT NULL,
    password_hash text NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS index_app_service_records_by_environment_id ON public.app_service_records USING btree (environment_id);

CREATE INDEX IF NOT EXISTS index_app_service_records_by_project_id ON public.app_service_records USING btree (project_id);

CREATE INDEX IF NOT EXISTS index_deployment_records_by_service_id ON public.deployment_records USING btree (service_id);

CREATE INDEX IF NOT EXISTS index_docker_credential_records_by_project_id ON public.docker_credential_records USING btree (project_id);

CREATE INDEX IF NOT EXISTS index_domain_records_by_service_id ON public.domain_records USING btree (service_id);

CREATE INDEX IF NOT EXISTS index_env_var_records_by_project_id ON public.env_var_records USING btree (project_id);

CREATE INDEX IF NOT EXISTS index_environments_by_project_id ON public.environments USING btree (project_id);

CREATE INDEX IF NOT EXISTS index_project_template_records_by_source_project_id ON public.project_template_records USING btree (source_project_id);

CREATE UNIQUE INDEX IF NOT EXISTS index_user_invite_records_by_token_hash ON public.user_invite_records USING btree (token_hash);

CREATE INDEX IF NOT EXISTS index_user_invite_records_by_user_id ON public.user_invite_records USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS index_user_records_by_email ON public.user_records USING btree (email);
