[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Tag               sango-platform
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /fluent-bit/state/flb_sango_platform.db
    Refresh_Interval  10
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On

[FILTER]
    Name   modify
    Match  sango-platform
    Add    telemetry_scope platform_only

[OUTPUT]
    Name            es
    Match           sango-platform
    Host            elasticsearch
    Port            9200
    HTTP_User       ${ELASTIC_USERNAME}
    HTTP_Passwd     ${ELASTIC_PASSWORD}
    Index           sango-platform-logs
    Type            _doc
    Logstash_Format On
    Include_Tag_Key On
    Tag_Key         docker_tag

